/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
soma_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("numeros para somar: %d e %d\n", argp->a, argp->b);
	result = argp->a + argp->b;

	return &result;
}

int *
subtracao_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("numeros para subtrair: %d e %d\n", argp->a, argp->b);
	result = argp->a - argp->b;	
	
	return &result;
}

int *
multiplicacao_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("numeros para multiplicar: %d e %d\n", argp->a, argp->b);
	result = argp->a * argp->b;

	return &result;
}

int *
divisao_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("numeros para dividir: %d e %d\n", argp->a, argp->b);
	result = argp->a / argp->b;

	return &result;
}

int *
potencia_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("numeros para o calculo da potencia: %d e %d\n", argp->a, argp->b);
	int acumulador = 1;
	for (int i = 0; i< argp->b; i++) {
		acumulador *= argp->a;
	}
	result = acumulador;

	return &result;
}
