/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
};
typedef struct numbers numbers;

#define SIMP_PROG 0x2fffffff
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  int * soma_1(numbers *, CLIENT *);
extern  int * soma_1_svc(numbers *, struct svc_req *);
#define subtracao 2
extern  int * subtracao_1(numbers *, CLIENT *);
extern  int * subtracao_1_svc(numbers *, struct svc_req *);
#define multiplicacao 3
extern  int * multiplicacao_1(numbers *, CLIENT *);
extern  int * multiplicacao_1_svc(numbers *, struct svc_req *);
#define divisao 4
extern  int * divisao_1(numbers *, CLIENT *);
extern  int * divisao_1_svc(numbers *, struct svc_req *);
#define potencia 5
extern  int * potencia_1(numbers *, CLIENT *);
extern  int * potencia_1_svc(numbers *, struct svc_req *);
extern int simp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  int * soma_1();
extern  int * soma_1_svc();
#define subtracao 2
extern  int * subtracao_1();
extern  int * subtracao_1_svc();
#define multiplicacao 3
extern  int * multiplicacao_1();
extern  int * multiplicacao_1_svc();
#define divisao 4
extern  int * divisao_1();
extern  int * divisao_1_svc();
#define potencia 5
extern  int * potencia_1();
extern  int * potencia_1_svc();
extern int simp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
