/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
simp_prog_1(char *host, int a, int b)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  soma_1_arg;
	int  *result_2;
	numbers  subtracao_1_arg;
	int  *result_3;
	numbers  multiplicacao_1_arg;
	int  *result_4;
	numbers  divisao_1_arg;
	int  *result_5;
	numbers  potencia_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SIMP_PROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	soma_1_arg.a = a;
	soma_1_arg.b = b;

	subtracao_1_arg.a = a;
	subtracao_1_arg.b = b;

	multiplicacao_1_arg.a = a;
	multiplicacao_1_arg.b = b;

	divisao_1_arg.a = a;
	divisao_1_arg.b = b;

	potencia_1_arg.a = a;
	potencia_1_arg.b = b;

	result_1 = soma_1(&soma_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("soma = %d\n", *result_1);
	}
	result_2 = subtracao_1(&subtracao_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("subtracao = %d\n", *result_2);
	}
	result_3 = multiplicacao_1(&multiplicacao_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("multiplicacao = %d\n", *result_3);
	}
	result_4 = divisao_1(&divisao_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("divisao = %d\n", *result_4);
	}
	result_5 = potencia_1(&potencia_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("potencia = %d\n", *result_5);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	simp_prog_1 (host, atoi(argv[2]), atoi(argv[3]));
exit (0);
}
